cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'
urlpatterns = [
    # path('', views.HomeView.as_view(), name='home'),
    path('', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('jsondata/', views.DataView.as_view(), name='jsondata'),
    path('jsondata/<index>', views.BookDataView.as_view(), name='dataofbook'),
    path('data/<index>',views.IndividualDataView.as_view(), name='data'),
    path('cart',views.CartDataView.as_view(), name='datacart'),
    path('checkout/',views.CheckoutView.as_view(), name='checkout'),
    path('cartdata/',views.CartView.as_view(), name='cart'),
    path('deleteitem/<index>',views.DeleteItemView.as_view(), name='deleteitem'),
    path('placeorder/',views.PlaceOrderView.as_view(), name='placeorder'),
    path('logout/',views.logout, name='logout'),



]

myproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('cart/', include('cart.urls')),
    path('admin/', admin.site.urls),
]

cart/models.py
import datetime

from django.db import models
from django.utils import timezone
from datetime import datetime


class Register(models.Model):
    Fullname = models.CharField(max_length=50)
    email = models.CharField(max_length=80, unique=True)
    password = models.CharField(max_length=15)
    phone = models.CharField(max_length=20)
    register_date = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.Fullname


class Cart(models.Model):
    id = models.AutoField(primary_key=True)
    email = models.CharField(max_length=80)
    BookId = models.CharField(max_length=100, unique=True)
    BookName = models.CharField(max_length=200, unique=True)
    Index = models.IntegerField()
    Price = models.FloatField()
    Quantity = models.IntegerField(default=1)

    def __str__(self):
        return self.BookName

cart/forms.py
from django import forms

class RegisterForm(forms.Form):
	name = forms.CharField(widget = forms.TextInput(attrs={'class' : 'form-control form-control-sm'}),label="Enter Your Name :")
	email = forms.CharField(widget = forms.EmailInput(attrs={'class' : 'form-control form-control-sm','placeholder':'example@gmail.com'}),label="Enter Mail Id :")
	password = forms.CharField(widget = forms.PasswordInput(attrs={'class' : 'form-control form-control-sm'}), label="Enter Password :")
	repassword = forms.CharField(widget = forms.TextInput(attrs={'class' : 'form-control form-control-sm'}),label="Confirm Password :")
	phone_no = forms.CharField(widget = forms.TextInput(attrs={'class' : 'form-control form-control-sm','placeholder':'+91 9999999'}),label="Enter Phone Number :")

class LoginForm(forms.Form):
	email = forms.CharField(widget = forms.EmailInput(attrs={'class' : 'form-control form-control-sm'}))
	password = forms.CharField(widget = forms.PasswordInput(attrs={'class' : 'form-control form-control-sm'}))

cart/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from .forms import LoginForm, RegisterForm
import json
from .models import Register, Cart
from django.http import JsonResponse
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_protect
from django.template import RequestContext


class HomeView(generic.TemplateView):
    template_name = "cart/home.html"

    def get(self, request):
        form = LoginForm()

        return render(request, self.template_name, {'form': form})


class RegisterView(generic.TemplateView):
    model = Register
    template_name = "cart/register.html"

    def get(self, request):
        form = RegisterForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            repassword = form.cleaned_data['repassword']
            phone_no = form.cleaned_data['phone_no']
            q1 = Register.objects.filter(email=email).get()
            if q1 != None:
                msg = "User already exist....."
                args = {'form': form, 'error': msg}
                return render(request, self.template_name, args)
            elif password == repassword:
                Reg = Register(Fullname=name, email=email, password=password, phone=phone_no)
                Reg.save()
                home = HomeView()
                return redirect('cart:login')
            else:
                msg = "Please enter correct password"
                args = {'form': form, 'error': msg}
                return render(request, self.template_name, args)


class LoginView(generic.TemplateView):
    model = Register
    template_name = "cart/login.html"

    def get(self, request):
        if request.session.has_key('username'):
            username = request.session['username']
            q2 = Cart.objects.filter(email=username).count()
            request.session['cart_items'] = q2
            return render(request, 'cart/page.html', {"username": username})
        return render(request, self.template_name)

    def post(self, request):
        if request.method == "POST":
            username = request.POST['Username']
            password = request.POST['password']
            request.session['username'] = username
            q1 = Register.objects.get(email=username)
            if password == q1.password:
                q2 = Cart.objects.filter(email=username).count()
                request.session['cart_items'] = q2
                return render(request, 'cart/page.html', {"username": username})
            else:
                msg = "Please enter correct UserName and Password"
                return render(request, self.template_name, {'error': msg})


class DataView(generic.TemplateView):
    template_name = "cart/page.html"

    def get(self, request):
        json_data = json.loads(open('cart/static/books.json').read())
        return HttpResponse(json.dumps(json_data))

    def post(self, request):
        return ""


class BookDataView(generic.TemplateView):
    template_name = "cart/individualpage.html"

    def get(self, request, index):
        index = int(index)
        json_data = json.loads(open('cart/static/books.json').read())
        data = json_data['items'][index]
        return HttpResponse(json.dumps(data))


class CartDataView(generic.TemplateView):
    template_name = "cart/individualpage.html"

    def post(self, request):
        bookid = request.POST['bookid']
        name = request.POST['name']
        price = request.POST['price']
        index = request.POST['index']
        email = request.session['username']
        try:
            q1 = Cart.objects.get(email=email, BookId=bookid)
        except Cart.DoesNotExist:
            q1 = None
        if q1 != None:
            q1.Quantity = q1.Quantity + 1
            q1.save()
            q2 = Cart.objects.filter(email=email).count()
            request.session['cart_items'] = q2
            return HttpResponse(q2)
        else:
            data = Cart(email=email, BookName=name, BookId=bookid, Index=index, Price=price)
            data.save()
            q2 = Cart.objects.filter(email=email).count()
            request.session['cart_items'] = q2
            return HttpResponse(q2)


class IndividualDataView(generic.TemplateView):
    template_name = "cart/individualpage.html"

    def get(self, request, index):
        args = {
            'username': request.session['username']
        }
        return render(request, self.template_name, args,)


class CartView(generic.TemplateView):
    template_name = "cart/cartpage.html"
    model = Cart

    def get(self, request):
        email = request.session['username']
        cartdata = Cart.objects.filter(email=email).all()
        data = []
        json_data = json.loads(open('cart/static/books.json').read())
        for cart in cartdata:
            index = int(cart.Index)
            item = json_data['items'][index]
            item['quantity'] = cart.Quantity
            item['amount'] = round((int(cart.Quantity) * cart.Price), 2)
            item['index'] = index
            data.append(item)
        return render(request, self.template_name, {'data': data})


class CheckoutView(generic.ListView):
    template_name = "cart/checkoutpage.html"
    model = Cart
    context_object_name = 'checkout_list'

    def get_queryset(self):
        email = self.request.session['username']
        return Cart.objects.filter(email=email).all()


class DeleteItemView(generic.TemplateView):
    template_name = "cart/cartpage.html"
    model = Cart

    def get(self, request, index):
        email = request.session['username']
        deleteitem = Cart.objects.filter(email=email, Index=index).delete()
        q1 = Cart.objects.filter(email=email).count()
        request.session['cart_items'] = q1
        return redirect("cart:cart")


class PlaceOrderView(generic.TemplateView):
    template_name = "cart/placeorder.html"

    def get(self, request):
        email = request.session['username']
        deleteitem = Cart.objects.filter(email=email).delete()
        q1 = Cart.objects.filter(email=email).count()
        request.session['cart_items'] = q1
        return render(request, self.template_name)


def logout(request):
    request.session.flush()
    return redirect("cart:login")

cart/templates/cart/base.html
<!DOCTYPE html>
<html>
<head>
	<title>{%block title%}{%endblock%}</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"></script>

  {% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'cart/css/bootstrap.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'cart/css/bootstrap.min.css' %}" />
<script type="text/javascript" src="{% static 'cart/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'cart/js/bootstrap.js' %}"></script>
<link rel="icon" type="image" href="{% static 'cart/img/msit.png' %}">
<link rel="stylesheet" type="text/css" href="{% static 'cart/css/styles.css' %}" />


	{%block script%}{%endblock%}
	{%block styles%}{%endblock%}
</head>
<body>
  <header>
  {% if  request.session.username %}
	<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <a class="navbar-brand" href="{% url 'cart:login' %}">MSIT Shopping App</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
          </li>
        </ul>
        <ul class="navbar-nav my-2 my-lg-0">
          <li class="nav-item">
            <a href="{% url 'cart:cart' %}" class="nav-link" id="CART">CART({{request.session.cart_items}})</a>
          </li>
          <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{request.session.username}}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'cart:logout' %}">Logout</a>
        </div>
      </li>
        </ul>
      </div>
    </nav>
    {% else %}
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
      <a class="navbar-brand" href="{% url 'cart:login' %}">MSIT Shopping App</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
      </div>
    </nav>
    {% endif %}
  </header>
    <div class="container" style="padding-top: 10px">
		{%block body%}{%endblock%}
	</div>
</body>
</html>

cart/templates/cart/cartpage.html
{%extends "cart/base.html"%}
{%block title%}Cart Page{%endblock%}
{%block body%}
{% if data %}
<div class="row" style="float: right;">
	<a href="{% url 'cart:checkout' %}" class="btn btn-warning">Checkout</a>
</div>
{% for item in data%}
<div class="card w-75 card border-dark mb-3">
  <div class="card-header">
    <a href="/cart/data/{{item.index}}">{{item.volumeInfo.title}}</a>
  </div>
  <div class="card-body">
    <div class="row">
    	<div class="col-md-4">
    		<img src="{{item.volumeInfo.imageLinks.thumbnail}}">
    	</div>
    	<div class="col-md-8">
    		<div class="row"><b>Price: </b> &#8377; {{item.saleInfo.listPrice.amount}}</div>
    		<div class="row"><b>Quantity: </b> {{item.quantity}}</div>
    		<div class="row"><b>Amount: </b> &#8377; {{item.amount}}</div>
    	</div>
    </div>
    <div class="row" style="float: right;">
    	<a href="/cart/deleteitem/{{item.index}}" class="btn btn-danger btn-sm">Delete</a>
    </div>
  </div>
</div>
<br>
{% endfor %}
{% endif %}

{%endblock%}

cart/templates/cart/checkoutpage.html
{%extends "cart/base.html"%}
{%block title%}Checkout Page{%endblock%}
{%block body%}
<script type="text/javascript">
	var sum=0.0;
</script>
<table class="table">
	<thead>
		<th>Id</th>
		<th>Name</th>
		<th>Price</th>
		<th>Quantity</th>
		<th>Amount</th>
	</thead>
	<tbody>
		{% for ch in checkout_list %}
		<tr>
		<td>{{forloop.counter}}</td>
		<td>{{ch.BookName}}</td>
		<td>{{ch.Price}}</td>
		<td>{{ch.Quantity}}</td>
		<td id="{{forloop.counter}}"></td>
		</tr>
		<script type="text/javascript">
			var Price={{ch.Price}};
			var q={{ch.Quantity}};
			var amount=(Price*q);
			sum+=amount;
			amount=amount.toFixed(2);
			document.getElementById("{{forloop.counter}}").innerHTML =amount+"";
		</script>
		{%endfor%}
		<tr>
			<td></td>
			<td></td>
			<td></td>

			<td><b>Total</b></td>
			<td id="total"></td>
		</tr>
		<script type="text/javascript">
			sum=sum.toFixed(2);
			document.getElementById("total").innerHTML=sum;
		</script>
	</tbody>
</table>
<div class="row" style="float:right;">
	<a href="{% url 'cart:placeorder'%}" class="btn btn-warning">Place Order</a>
</div>
{%endblock%}

cart/templates/cart/home.html
{%extends "cart/base.html"%}
{%block title%}Home Page{%endblock%}
{%block body%}

<div class="card">
  <div class="card-header">
    Login :
  </div>
  <div class="card-body">
  	{% if error %}
    <p style="color: red;">{{error}}</p>
    {% endif %}
  	<form method="POST">
  		{% csrf_token %}
  		{{form.as_p}}
  		<br>
  		<a href="{% url 'cart:register'%}">Register Here!!!</a>
  		<br>
  		<button type="submit" class="btn btn-primary">Login</button>
  	</form>
  </div>
</div>

{%endblock%}

cart/templates/cart/individualpage.html
{%extends "cart/base.html"%}
{%block title%}Book Page{%endblock%}
{%block body%}
<script type="text/javascript">
	var Jsondata;
	var cart_items;
	var link;
	function Response() {
		link=window.location.toString();
		link=link.split("/");
		// console.log(window.location.toString()," ///// ",link);
		$.ajax({
			type: 'get',
			url: '/cart/jsondata/'+link[link.length-1],
			dataType: 'json',
			success: function(data)
			{
				Jsondata=data;
				console.log(data," ///// ",typeof(data));
    			document.getElementById("title").innerHTML =data.volumeInfo.title;
			    document.getElementById("desc").innerHTML = data.volumeInfo.description;
			    document.getElementById("bookpic").src = data.volumeInfo.imageLinks.thumbnail;
			    document.getElementById("authors").innerHTML ="<b>Author : </b>"+data.volumeInfo.authors;
			    document.getElementById("amt").innerHTML ="<b>Price : </b>"+ '&#8377; ' + amount(data);
			    document.getElementById("publisher").innerHTML ="<b>Publisher : </b>"+data.volumeInfo.publisher;
			    document.getElementById("dop").innerHTML = data.volumeInfo.publishedDate;
			    document.getElementById('Cart').onclick=function(){cart(data)};
			    document.getElementById('Buy').onclick=function(){cart(data)};
			}
		});
	}
	$(document).ready(function(){
		Response();
	});

	function amount(data) {
    var temp1 = "";
    var str='';
    if (data.saleInfo.listPrice)
        temp1 = temp1 + data.saleInfo.listPrice.amount;
    else {
    	document.getElementById('Cart').disabled = true;
		document.getElementById('Buy').disabled = true;
		str+='<a href="'+data.volumeInfo.previewLink+'" class="btn btn-primary" target="_blank">More Info</a>'
		document.getElementById("moreinfo").innerHTML =str ;
        temp1 = temp1 + "Not available";
    }
    return temp1;
}

function cart(dat)
{
	var data={
		'bookid':dat.id,
		'name':dat.volumeInfo.title,
		'index': link[link.length-1],
		'price':amount(dat),
		csrfmiddlewaretoken: $("input[name='csrfmiddlewaretoken']").val(),
	};
	console.log("In cart");
	$.ajax({
		type: 'post',
		url: '/cart/cart',
		data:data,
		success:function(data)
		{
			console.log(data,typeof(data));
			document.getElementById("CART").innerHTML="CART("+data+")";

		}
	});
}


</script>

<div class="row">
	<div class="col-md-5">
		<div class="row">
			<div class="col-md-5">
				<img src="" width="100%" height="200px" id="bookpic">
			</div>
			<div class="col-md-7">
					<div id="authors"></div>
					<div id="publisher"></div>
					<div id="amt"></div>
					<div id="dop"></div>
			</div>
		</div>
		<br>
		<div class="row">
			<div class="col-md-10">
				<button class="btn btn-warning btn-block" id="Cart" >Add To Cart</button>
			</div>
		</div>
		<br>
		<div class="row">
			<div class="col-md-10">
				<button class="btn btn-warning btn-block" id="Buy">Buy Now</button>
			</div>
		</div>
	</div>
	<div class="col-md-7">
		<div class="row">
			<h1 id="title"></h1>
		</div>
		<div class="row">
			<p id="desc"></p>
		</div>
		<div class="row" id="moreinfo">
		</div>
	</div>


<div class="hidden">
     <form class="default_form">
           {% csrf_token %}
     </form>
</div>


</div>
{%endblock%}

cart/templates/cart/login.html
{%extends "cart/base.html"%}
{%block title%}Login Page{%endblock%}
{%block body%}

<div class="card">
  <div class="card-header">
    Login :
  </div>
  <div class="card-body">
    {% if error %}
    <p style="color: red;">{{error}}</p>
    {% endif %}
  	<form method="POST">
  		{% csrf_token %}
      <div class="form-group">
        <label>UserName:</label>
        <input type="text" name="Username" class="form-control form-control-sm" required="required">
      </div>
      <div class="form-group">
        <label>Password:</label>
        <input type="password" class="form-control form-control-sm" name="password" required="required">
      </div>
      <div class="form-group">
        <a href="{% url 'cart:register'%}">Register Here!!!</a>
      </div>
  		<button type="submit" class="btn btn-primary">login</button>
  	</form>
  </div>
</div>

{%endblock%}

cart/templates/cart/page.html
{%extends "cart/base.html"%}
{%block title%}Home Page{%endblock%}
{%block script%}
<script type="text/javascript">
	var Jsondata;
	function getResponses() {
		$.ajax({
			type: 'get',
			url: "{% url 'cart:jsondata'%}",
			dataType: 'json',
			success:function(data){
				Jsondata=data;
				console.log("nnnn ",data,typeof(data)," ////// ","{% url 'cart:jsondata'%}");
				show(0,data);
			}
		});
	}
	$(document).ready(function(){
		getResponses();
	});
</script>
<script type="text/javascript">
	var index=0;
	var Data;
	var arrays;
	function display(a)
	{
		console.log(a," display");
		var count=0,b=a+12;
		if(b>=arrays.length)
		{
			b=arrays.length;
		}
		var str='<div class="row">';
		for (var i = a; i <b; i++) {
			count++;
			str+='<div class="col-md-3">';
			str+='<div class="card card border-dark mb-3" style="width: 15rem;">';
  			str+='<img class="card-img-top" src="'+arrays[i].volumeInfo.imageLinks.thumbnail+'" alt="Card image cap" style="height:150px">';
  			str+='<div class="card-body" id="Cards">'
    		str+='<a href="/cart/data/'+i+'"><h5 class="card-title">'+arrays[i].volumeInfo.title+'</h5></a>';
  			str+='</div></div>';
			str+='</div>';
			if (count>=4) {
				count=0;
				str+='</div><br/>';
				str+='<div class="row">';
			}
		}
		str+='</div>'
		document.getElementById("my").innerHTML =str;
	}

	function prev()
    {
      index-=12;
      show(index,Data);

    }
    function next()
    {
      index+=12;
      show(index,Data);
    }
    function show(i,data)
    {
    	Data=data;
    	arrays=data.items;
      var p=document.getElementById("prev");
      var q=document.getElementById("next");
      if(arrays.length<=12)
      {
      	p.style.display="none";
        q.style.display="none";
      }
      else if(i<=0){
        p.style.display="none";
        q.style.display="block";
      }
      else if(i>=arrays.length-12){
        q.style.display="none";
        p.style.display="block";
      }
      else
      {
        q.style.display="block";
        p.style.display="block";
      }
      display(index);

    }
</script>


{%endblock%}
{%block body%}
<div class="container">
<div id="my"></div>
<div class="row">
	<div class="col-md-11">
		<button class="btn btn-primary" id="prev" onclick="prev();">Prev</button>
	</div>
	<div class="col-md-1">
		<button class="btn btn-primary" id="next" onclick="next();" style="float: right;">Next</button>
	</div>
</div>

</div>
{%endblock%}

cart/templates/cart/placeorder.html
{%extends "cart/base.html"%}
{%block title%}Order Page{%endblock%}
{%block body%}
<div class="row placeorder"><h1>Successfully Placed Order</h1></div>
<div class="row placeorder"><h3>Thank You!!!</h3></div>
<div class="row placeorder"><h5>Visit again</h5></div>
</div>
{%endblock%}

cart/templates/cart/register.html
{%extends "cart/base.html"%}
{%block title%}Signup Page{%endblock%}
{%block body%}

<div class="card">
  <div class="card-header">
     Register :
  </div>
  <div class="card-body">
    {% if error %}
    <p style="color: red;">{{error}}</p>
    {% endif %}
  	<form method="POST">
  		{% csrf_token %}
  		{{form.as_p}}
      <br>
  		<button type="submit" class="btn btn-primary">Register</button>
  	</form>
  </div>
</div>

{%endblock%}